### ISSUE TITLE
1.5.0 Pipeline

### ISSUE THREAD

**Issue by MarkehMe** [redstone/LegacyFactions#201]
This is the currently pipeline for the 1.5.0 release.

## Internal 
- [ ] MySQL Support
- [ ] Locality API throughout:
- - [ ] Land Ownerships 
- - [ ] Claims

## Ownerships
- [ ] Toggle to not give faction moderators access to owned land #8 
- [ ] /f access: add yes/all and no/none #25

## Faction
- [ ] Max members, allies, and enemies #42
- [ ] Allow breaking certain blocks in other territories #105
- [ ] Land-based permissions  #41
- [ ] Land Value Multiplier #43

## Bug Fixes 
- [ ] Armour Stands and Item Frames are breakable #142
## New Expansions
- [ ] Faction Upgrades 
- - [ ] Upgrade Max members, allies, and enemies #42

**Comment by MarkehMe** [comment]
Hello! 😄  

I'm a Herobrine - the friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf.json` file! Put it on pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks,**
Herobrine
*RedstoneOre Projects Bot*


*I am a bot, I don't respond after this!*

**Comment by MarkehMe** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf.json` file! Put it on pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by MarkehMe** [comment]
Hello! 😄  

This is a friendly autoresponder to ensure you've done a few things.

## For issues, bug reports, and **even simple help**:

1) Provide the contents of `/f debug` - this gives us some helpful information about your server.
2) Provide the output of `/version` - we need the exact version, with the weird numbers and letters!
3) Provide your entire server log! Put it on pastebin.com and supply the link.
4) Provide your `plugins/LegacyFactions/conf` file! Put it on www.pastebin.com and supply the link.

If you ignore these questions your issue will get fixed slower, and possibly just get closed as invalid because you didn't explain it properly 😞

## For features:

1) Please be as descriptive as possible! More is better than less!
2) If you can, provide pictures, or if an existing plugin has something similar - provide a link!


**Thanks**

*This is an automatic message! Please respond saying you have done these things.*

**Comment by DuckCraftPvP** [comment]
https://www.youtube.com/watch?v=NFxeq9_P5xo F access can you add that and also a GUI to edit it?
https://forum.cosmicpvp.com/threads/f-access-and-f-perm-update.269134/

and /f perm  - That cosmic thread above should give you all info you need.
